name: ios
on: push

defaults:
  run:
    shell: bash
    working-directory: iosApp

jobs: 
  build:
    name: "iOS test"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Select Xcode"
        run: sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: "Install xcpretty"
        run: gem install xcpretty
      - name: Make Gradle executable
        run: chmod +x ../gradlew
      - name: Create XCFramework
        run: ./scripts/create-xcframework.sh
        shell: bash
      - name: Xcode Build
        run: |
          set -o pipefail &&
          xcodebuild \
          -project iosApp.xcodeproj \
          -destination 'platform=iOS Simulator,name=iPhone 12' \
          -sdk iphonesimulator \
          -scheme iosApp \
          -configuration Debug \
          clean build | xcpretty
