name: ios
on: push

defaults:
  run:
    shell: bash
    working-directory: iosApp

jobs: 
  build:
    name: "iOS test"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Select Xcode"
        run: sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer
      - name: "Install xcpretty"
        run: gem install xcpretty
      - name: Xcode Build
        run: |
          set -o pipefail &&
          xcodebuild 
        -project iosApp.xcodeproj[]
          -destination 'platform=iOS Simulator,name=iPhone 12'
          -sdk iphonesimulator
          -scheme iosApp
          -configuration Debug
          --allowProvisioningUpdates
          --allowProvisioningDeviceRegistration
          clean build | xcpretty